### ISSUE TITLE
initial setup credit system and credit verification.

### ISSUE THREAD

**Issue by malek10xdev** [ankaboot-source/leadminer#1099]
related to https://github.com/ankaboot-source/leadminer.io/issues/203

## TODO

- [x] add users table to manage user data created with a trigger on signup
- [x] add column `total_credits` to users table.
- [x] add credit verification & credit deduction to CSV endpoint

>  For the moment the user account will be initialized with 1500 credits as mentioned in the free plan. 

**Notes from last weekly:**
- credit-related code should be in a separate file (function and get's called)
- add feature-flag to enable/disable credit verification
- fix the correct status codes / and verification logic
